# --- !Ups

create table "USER" ("ID" BIGSERIAL NOT NULL PRIMARY KEY,"NAME" VARCHAR NOT NULL);
create table "MOVIE" ("ID" BIGSERIAL NOT NULL PRIMARY KEY,"NAME" VARCHAR NOT NULL, "IMDB" VARCHAR NOT NULL, "USER_ID" BIGINT);

# --- !Downs

drop table "MOVIE";
drop table "USER";